import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import clsx from 'clsx'
import { Aside } from '@/src/components/layout/Aside'
import { Header } from '@/src/components/layout/Header'
import { Footer } from '@/src/components/layout/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full" >
      <body className={clsx(inter.className, 'h-full bg-background')}>
        <div className="flex h-full max-w-6xl mx-auto py-10 sm:py-0 ">
          <Aside />
          <main>
            <Header />
            <div className="p-2">
              {children}
            </div>
            <Footer />
          </main>
        </div>
      </body>
    </html>
  )
}
