const Globals = {
    title: "Twitter Not Dead",
    logo: "/images/twitter-logo.png",
    meta: {
      title: 'Create Next App',
      description: 'Generated by create next app',
    }
}

export default Globals